"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Loader2, MapPin, ArrowRight } from "lucide-react";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { ApiError } from "@/lib/api/client";
import { getCustomerShipment, type Shipment } from "@/lib/api/orders";
export default function ShipmentDetailPage() { const { id } = useParams<{ id: string }>(); const [shipment, setShipment] = useState<Shipment | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { if (id) getCustomerShipment(id).then(setShipment).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to load shipment.")); }, [id]); if (error) return <div className="max-w-[1280px] mx-auto py-16 text-center text-[#B42318]">{error}</div>; if (!shipment) return <div className="flex justify-center py-20 text-[#44474d]"><Loader2 size={22} className="animate-spin mr-2" /> Loading shipment…</div>; return <div className="max-w-[1280px] mx-auto space-y-6"><div className="flex items-center gap-3"><Link href="/portal/shipments" className="p-2 text-[#44474d] hover:text-[#0B1F3A] rounded hover:bg-[#e8eeff]"><ArrowLeft size={20} /></Link><h1 className="font-headline-lg text-[#111c2d]">{shipment.trackingNumber ?? shipment.shipmentNumber}</h1><StatusBadge status={shipment.status.toLowerCase()} /></div><div className="bg-white rounded-lg border border-[#E4E7EC] p-6"><h2 className="font-headline-sm text-[#111c2d] mb-4">Shipment Route</h2><div className="flex items-center gap-4"><div className="font-label-md text-center"><MapPin size={20} className="mx-auto text-[#0B1F3A]" /><p>{shipment.origin ?? "—"}</p><small>Origin</small></div><ArrowRight size={22} className="text-[#1769E0]" /><div className="font-label-md text-center"><MapPin size={20} className="mx-auto text-[#12B76A]" /><p>{shipment.destination ?? "—"}</p><small>Destination</small></div></div><div className="grid grid-cols-3 gap-4 mt-6 pt-6 border-t border-[#E4E7EC]"><div><p className="font-label-sm text-[#44474d]">Carrier</p><p>{shipment.carrier ?? "—"}</p></div><div><p className="font-label-sm text-[#44474d]">ETA</p><p>{shipment.eta?.split("T")[0] ?? "—"}</p></div><div><p className="font-label-sm text-[#44474d]">Order</p><p>{shipment.salesOrder?.orderNumber ?? "—"}</p></div></div></div></div>; }
