"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Loader2 } from "lucide-react";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { ApiError } from "@/lib/api/client";
import { getCustomerInvoice, type Invoice } from "@/lib/api/orders";
function money(value: string | number, currency: string) { return `${currency} ${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`; }
export default function InvoiceDetailPage() { const { id } = useParams<{ id: string }>(); const [invoice, setInvoice] = useState<Invoice | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { if (id) getCustomerInvoice(id).then(setInvoice).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to load invoice.")); }, [id]); if (error) return <div className="max-w-[1280px] mx-auto py-16 text-center text-[#B42318]">{error}</div>; if (!invoice) return <div className="flex justify-center py-20 text-[#44474d]"><Loader2 size={22} className="animate-spin mr-2" /> Loading invoice…</div>; return <div className="max-w-[1280px] mx-auto space-y-6"><div className="flex items-center gap-3"><Link href="/portal/invoices" className="p-2 text-[#44474d] hover:text-[#0B1F3A] rounded hover:bg-[#e8eeff]"><ArrowLeft size={20} /></Link><h1 className="font-headline-lg text-[#111c2d]">{invoice.invoiceNumber}</h1><StatusBadge status={invoice.status.toLowerCase()} /></div><div className="bg-white rounded-lg border border-[#E4E7EC] p-8 shadow-sm"><div className="flex justify-between mb-8 pb-8 border-b border-[#E4E7EC]"><div><p className="font-headline-sm text-[#0B1F3A]">Compex Solution</p><p className="font-body-sm text-[#44474d]">B2B Electronics Procurement</p></div><div className="text-right"><p className="font-headline-md text-[#0B1F3A]">INVOICE</p><p className="font-body-sm text-[#44474d]">Issued: {(invoice.issuedAt ?? invoice.createdAt).split("T")[0]}</p><p className="font-body-sm text-[#44474d]">Due: {invoice.dueDate?.split("T")[0] ?? "—"}</p></div></div><p className="font-label-md text-[#111c2d] mb-6">Order: {invoice.salesOrder?.orderNumber ?? "—"}</p><div className="overflow-x-auto"><table className="w-full min-w-[600px]"><thead><tr className="bg-[#0B1F3A] text-white"><th className="py-3 px-4 text-left font-label-sm">Description</th><th className="py-3 px-4 text-right font-label-sm">Qty</th><th className="py-3 px-4 text-right font-label-sm">Unit Price</th><th className="py-3 px-4 text-right font-label-sm">Total</th></tr></thead><tbody className="divide-y divide-[#E4E7EC]">{invoice.items.map((item) => <tr key={item.id}><td className="py-3 px-4">{item.description ?? item.mpn}</td><td className="py-3 px-4 text-right">{item.quantity}</td><td className="py-3 px-4 text-right">{money(item.unitPrice, invoice.currency)}</td><td className="py-3 px-4 text-right">{money(item.lineTotal, invoice.currency)}</td></tr>)}</tbody></table></div><div className="flex justify-end mt-6"><div className="w-72 space-y-2 text-right"><p>Subtotal: {money(invoice.subtotal, invoice.currency)}</p><p>Tax: {money(invoice.tax, invoice.currency)}</p><p className="font-label-md border-t border-[#E4E7EC] pt-2">Total: {money(invoice.total, invoice.currency)}</p></div></div></div></div>; }
