"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Search, Download, Loader2, Truck, Package, CheckCircle, Plane } from "lucide-react";
import { ApiError } from "@/lib/api/client";
import { listAdminShipments, type Shipment, type ShipmentStatus } from "@/lib/api/orders";

const STATUS: Record<ShipmentStatus, { label: string; color: string; icon: typeof Package }> = {
  PROCESSING: { label: "Processing", color: "bg-[#F79009]/10 text-[#F79009]", icon: Package }, IN_TRANSIT: { label: "In Transit", color: "bg-[#1769E0]/10 text-[#1769E0]", icon: Truck }, CUSTOMS: { label: "Customs", color: "bg-[#7B61FF]/10 text-[#7B61FF]", icon: Plane }, OUT_FOR_DELIVERY: { label: "Out for Delivery", color: "bg-[#F79009]/10 text-[#F79009]", icon: Truck }, DELIVERED: { label: "Delivered", color: "bg-[#12B76A]/10 text-[#12B76A]", icon: CheckCircle }, CANCELLED: { label: "Cancelled", color: "bg-[#F04438]/10 text-[#F04438]", icon: Package },
};
const TABS: ("All" | ShipmentStatus)[] = ["All", "PROCESSING", "IN_TRANSIT", "CUSTOMS", "OUT_FOR_DELIVERY", "DELIVERED"];

export default function AdminShipmentsPage() {
  const [shipments, setShipments] = useState<Shipment[]>([]); const [search, setSearch] = useState(""); const [tab, setTab] = useState<"All" | ShipmentStatus>("All"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => { setLoading(true); listAdminShipments({ status: tab === "All" ? undefined : tab, limit: 100 }).then((r) => { setShipments(r.data); setError(null); }).catch((e) => setError(e instanceof ApiError ? e.message : "Unable to load shipments.")).finally(() => setLoading(false)); }, [tab]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => { const q = search.toLowerCase(); return shipments.filter((s) => !q || s.shipmentNumber.toLowerCase().includes(q) || s.trackingNumber?.toLowerCase().includes(q) || s.carrier?.toLowerCase().includes(q) || s.salesOrder?.orderNumber.toLowerCase().includes(q)); }, [shipments, search]);

  return <div className="space-y-6"><div className="flex items-end justify-between"><div><h1 className="font-headline-lg text-[#111c2d]">Import & Shipments</h1><p className="font-body-md text-[#44474d]">{loading ? "Loading…" : `${shipments.length} live shipments`}</p></div><button className="flex items-center gap-2 border border-[#E4E7EC] bg-white px-4 py-2 rounded font-label-md text-sm text-[#111c2d] hover:bg-[#f0f3ff]"><Download size={15} /> Export</button></div>
    <div className="flex flex-wrap gap-3 items-center"><div className="relative flex-1 min-w-[200px] max-w-sm"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#44474d]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search tracking # or carrier..." className="w-full pl-9 pr-4 py-2 bg-white border border-[#E4E7EC] rounded text-sm focus:outline-none focus:ring-2 focus:ring-[#1769E0]" /></div><div className="flex flex-wrap gap-1 bg-[#f0f3ff] p-1 rounded-lg">{TABS.map((s) => <button key={s} onClick={() => setTab(s)} className={`px-3 py-1.5 rounded font-label-sm text-xs whitespace-nowrap transition-colors ${tab === s ? "bg-white text-[#0B1F3A] shadow-sm" : "text-[#44474d] hover:text-[#0B1F3A]"}`}>{s === "All" ? s : s.replaceAll("_", " ")}</button>)}</div></div>
    {error && <div role="alert" className="rounded-lg border border-[#F04438]/30 bg-[#FEF3F2] px-4 py-3 text-[#B42318] flex justify-between"><span>{error}</span><button onClick={load} className="font-label-sm underline">Retry</button></div>}
    {loading && <div className="flex justify-center py-16 text-[#44474d]"><Loader2 size={22} className="animate-spin mr-2" /> Loading shipments…</div>}
    {!loading && !error && <div className="bg-white rounded-xl shadow-sm border border-[#E4E7EC] overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left whitespace-nowrap"><thead><tr className="bg-[#f0f3ff] border-b border-[#E4E7EC]">{["Shipment", "Tracking #", "Order", "Carrier", "Route", "ETA", "Status"].map((h) => <th key={h} className="px-5 py-3.5 font-label-sm text-[#44474d] uppercase tracking-wider text-xs">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#E4E7EC]">{filtered.map((s) => { const current = STATUS[s.status]; const Icon = current.icon; return <tr key={s.id} className="hover:bg-[#f0f3ff]/40 transition-colors"><td className="px-5 py-4 font-mono-label text-[#0B1F3A] font-medium text-sm">{s.shipmentNumber}</td><td className="px-5 py-4 font-mono-label text-[#44474d] text-xs">{s.trackingNumber ?? "—"}</td><td className="px-5 py-4 font-mono-label text-[#44474d] text-sm">{s.salesOrder?.orderNumber ?? "—"}</td><td className="px-5 py-4 font-body-sm text-[#111c2d] text-sm">{s.carrier ?? "—"}</td><td className="px-5 py-4 font-body-sm text-[#111c2d] text-xs">{s.origin ?? "—"} → {s.destination ?? "—"}</td><td className="px-5 py-4 font-body-sm text-[#44474d] text-sm">{s.eta?.split("T")[0] ?? "—"}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full font-label-sm text-xs ${current.color}`}><Icon size={11} />{current.label}</span></td></tr>; })}{filtered.length === 0 && <tr><td colSpan={7} className="py-12 text-center font-body-md text-[#44474d]">No shipments found.</td></tr>}</tbody></table></div></div>}
  </div>;
}
